services:
  discovery-server:
    image: book-discovery-server
    container_name: discovery-server
    ports:
      - 8761:8761
    networks:
      - ms-network
  api-gateway:
    image: book-apigateway-server
    container_name: book-api-gateway
    ports:
      - 8095:8095
    environment:
      EUREKA_HOST: discovery-server
    networks:
      - ms-network
    depends_on:
      - discovery-server
  book-service:
    image: book-bookservice-server
    build:
      context: ../BookService
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    container_name: book-service
    environment:
      EUREKA_HOST: discovery-server
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: password
    networks:
      - ms-network
    depends_on:
      - discovery-server
  customer-service:
    container_name: customer-service
    image: book-customerservice-serve
    build:
      context: ../CustomerService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      EUREKA_HOST: discovery-server
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: password
    depends_on:
      - discovery-server
    networks:
      - ms-network
  order-service:
    container_name: orde-service
    image: book-orderservice-server
    build:
      context: ../OrderService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      EUREKA_HOST: discovery-server
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: password
    depends_on:
      - discovery-server
    networks:
      - ms-network
networks:
  ms-network:
    driver: bridge